### PR TITLE
Fix build on musl

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by ulm** [comment]
AFAICS this undefines `REGEX` unconditionally? I don't think that this would be wanted on non-musl systems.

**Comment by hboetes** [comment]
Hello @kraj 

Thanks for your PR.

- Could you explain the rationale behind your PR i.e. show the output of `make clean all >& /dev/null; make`
- This PR feels like a workaround, which only circumvents the problem by simply cutting out a feature, but does not fix the root cause of the problem.

**Comment by kraj** [comment]
> AFAICS this undefines `REGEX` unconditionally? I don't think that this would be wanted on non-musl systems.

right, I have removed that patch. But the rest two should improve portability as they make it easy to compile on musl based systems

**Comment by hboetes** [comment]
@kraj 

Thanks for the update, I'll have a further look on it in the coming days.

**Comment by hboetes** [comment]
Hello @kraj,

I just tried to reproduce the problem, but I couldn't. The current code simply compiles and runs. Please let me know if you still think your PR is still relevant.

**Comment by kraj** [comment]
@hboetes what environment did you try it on? If its not yocto then it might have some patches done to musl etc. which might hide these issues. Let me also double check with latest tip and see if something has indirectly fixed it.

**Comment by hboetes** [comment]
Hello @kraj
Thanks for your reply.  I used my `generate-mg-static` script which uses alpine docker to generate the static binaries.

Does yocto use an unpatched version of muslibc?

**Comment by hboetes** [comment]
Appears to have been solved.

**Pull request closed without merging**
