### PR TITLE
[CMake] Fix compilation error with CMake

### PR DESCRIPTION
**Pull request by liangfu**
This PR adds interpreter.c in the list of source files to be compiled. Without the fix, the compilation with CMake fails into undefined reference to functions like `foundparen`.

@hboetes Please review.

### CODE REVIEW

**Comment by hboetes** [comment]
Hello Lianfun,

excellent catch! With one small problem, now you unconditionally set `GNU_SOURCE` on all platforms and it should only be set on Linux. Can you improve that?

Thanks!

**Comment by liangfu** [comment]
Sure, fixed! Please take another look.

**Comment by hboetes** [comment]
Hello @mazocomp,
what do you think of this pull request? You're the original artist of the CMake setup.

**Comment by hboetes** [comment]
A shame he never replied and I forgot about it.

**Pull request merged**
