### PR TITLE
Update mg.1 for display-wide-characters branch

### PR DESCRIPTION
**Pull request by mazocomp**
BTW, won't you mind if I send a patch to upstream to have UTF-8 support in mg in base?
I already have prepared a diff: https://pastebin.com/aNH7q9mK

### CODE REVIEW

**Comment by mazocomp** [comment]
I see it's still experimental, because I get tedious cursor movement bugs.

**Comment by hboetes** [comment]
No, it’s a free world. I have no say on what you post or don’t post. Have
you already seen this branch?
https://github.com/hboetes/mg/tree/display-wide-characters

**Comment by mazocomp** [comment]
@hboetes yes, I've seen. I'm asking because I'd like to know maybe there are more bugs which make it not ready for import. Ok, diff sent to tech@ mailing list: https://marc.info/?l=openbsd-tech&m=152753243329599&w=2

**Comment by hboetes** [comment]
@s-gilles is this interesting for your branch?

**Comment by s-gilles** [comment]
Regarding sending to -tech, I already sent it upstream back in 2016
(https://marc.info/?l=openbsd-tech&m=145338987910327). The size and
complexity of the patch appeared to be a deal-breaker then, so I've
decided to not bother them since. It's a free world, of course.

Regarding updating mg.1, the patch seems completely correct, and I
should have done that: merged.

Regarding the cursor movement: it was a completely intentional
design choice at the time (I believe my reasoning was that I wanted
to preserve movement, whether raw was shown or not), but I agree
that choice was a mistake, it probably should be changed. I'll see
if I remember the code well enough to make it behave more as expected.

-- 
S. Gilles

**Comment by mazocomp** [comment]
@s-gilles Good, there is only one bug left: incorrect detection of words.
One word may count as three words and three words may count as one word.

**Comment by s-gilles** [comment]
I'm not really sure what you mean. I'm using the classic UTF-8 demo
(https://cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt), M-f and
M-b seem to correctly skip between words. That's what I think of
when I think of 'detection of words', but perhaps you mean something
different. Could you give me an example of a file, some keyboard
input, and expected behavior?

-- 
S. Gilles

**Comment by s-gilles** [comment]
Ah, on second look I think I see it. I had been looking at the
ancient Greek section, which by pure coincidence works fine, but
in the Cyrillic section things start breaking. This appears
to be because ISWORD & co. (in chrdef.h) are extremely optimized
for ASCII.

This might be a pain in the neck: I worry that wctype(3) might not
be a good enough replacement for the macros, or may not be implemented
everywhere we need it. I'll try, but the fastest way out might just
be to consider every wide character to be ISWORD, and shrug if
somebody complains that a double standard is being applied to
"foo[bar]" vs. "foo⁅bar⁆".

-- 
S. Gilles

**Comment by mazocomp** [comment]
On Wed, May 30, 2018 at 06:22:37AM -0700, Han Boetes wrote:
> @s-gilles @mazocomp Please check the comments in this thread: https://marc.info/?t=152753252500001&r=1&w=2
> They contain interesting comments from the developers.
>

I know, I'm subscribed to that list.
I've already sent Stefan Sperling's comments to S. Gilles

**Comment by s-gilles** [comment]
I, too, am subscribed. I'm currently reading through a thousand
lines of unsnipped, inline diffs. 

-- 
S. Gilles

**Comment by hboetes** [comment]
Well I hope they pick up on my kind request.

**Comment by mazocomp** [comment]
@s-gilles While your changes are not ready to merge, I created a port: https://github.com/jasperla/openbsd-wip/commit/4842801acecf5394ba72293e2dfe29da71eb9fba

**Comment by mazocomp** [comment]
@hboetes @s-gilles btw, mg doesn't update often. so what do you think about tagging a new release after each sync with upstream to make packaging easier?

**Comment by s-gilles** [comment]
Sounds reasonable, but I don't think this will ever be merged: it's
a pretty in-depth patch, I'm a drive-by contributor, OpenBSD generally
prefers to do work like this themselves, and Theo's comments regarding
priorities are entirely reasonable. Back in 2016, I got the same
feeling, which is why I never pushed for a merge myself.

I believe it's far more likely that somebody at a hackathon, now
knowing that users want this functionality, decides to entirely
rewrite mg's guts and incidentally adds UTF-8 support. In the
meantime, I'll occasionally keep my branch synced with upstream,
and perhaps fix bugs if it takes reasonable effort, but I'm not
planning on being proactive about this. I met my use-case and
informed upstream to prevent others from unknowingly doing redundant
work -- that is sufficient for me.

-- 
S. Gilles

**Comment by mazocomp** [comment]
@hboetes I think this will be merged, all it needs is just a little polishing and 8-bit clean code. OpenBSD is happy to have contributors and testers. But since this is about quality, it will take a lot of time to make merge happen. Meanwhile I created a port only to make testing easier, I can just easily update and install UTF-8 fork. I remember how long it took me to get Tox in ports tree...

**Comment by mazocomp** [comment]
@hboetes @s-gilles today was a minor commit to mg(1) :)

**Comment by hboetes** [comment]
I just synced with CVS.

**Comment by s-gilles** [comment]
Synced with upstream. To make this work with wide characters, one
would need to

 - change isupper and toupper to work on wide characters (not
   impossible).

 - change the region_put_data bits to work if the towupper/towlower
   stuff changes the size of the buffer (pretty bad, and the only
   examples I know of that might cause this are the Turkish i and
   the German long s)

 - translate and/or interpret plen as a character limit, not a byte
   limit (nontrivially painful), which leads into

 - make re_search.c and search.c calculate plen correctly.

That last gets into "complete rewrite" territory, sadly. But it
seems to work fine with ASCII.

-- 
S. Gilles

**Pull request merged**
